[project]
name = "nornir-rich"
version = "0.3.0"
description = "Collection of 'nice looking' functions with rich for nornir"
authors = [
    {name = "ubaumann", email = "github@m.ubaumann.ch"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
]
dependencies = [
    "nornir>=3",
    "rich>=12",
]
[dependency-groups]
dev = ["pytest>=9", "black[jupyter]>=24", "mypy>=1", "ipykernel"]

[tool.mypy]
python_version = "3.8"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
strict_optional = true
warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true
